application: slice-game
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: client
- url: /.*
  script: _go_app
# - url: /_ah/remote_api
#   script: _go_app
#   login: admin